// Original teaching material. Source titles identify the official ICF framework;
// examples and explanations are editorial, not ICF assessment criteria.
export const p = (ro,en) => ({ro,en});
export const sources = {
  icf: 'https://coachingfederation.org/resource/icf-core-competencies/',
  pdf: 'https://coachingfederation.org/wp-content/uploads/2025/09/icf-cs-core-competencies-2025.pdf',
  romanian: 'https://coachingfederation.ro/competentele-de-baza-icf-2025/',
  playlist: 'https://www.youtube.com/playlist?list=PLMBtOVpaN5Dh-I78cax9v9FvxGCrfWhkR',
  grow: 'https://www.performanceconsultants.com/resources/the-grow-model/',
  book: 'https://www.performanceconsultants.com/resources/coaching-for-performance-book/',
  oskar: 'https://www.thesolutionsfocus.co.uk/about-us/',
  clear: 'https://assets.henley.ac.uk/defaultUploads/19.RES.057-Manifesto-for-Supervision-2019-online.pdf',
  habit: 'https://www.mbs.works/wp-content/uploads/2021/06/CoachingHabit_PeekOpeningChapters.pdf',
  toolkit: 'https://uk.sagepub.com/sites/default/files/upm-binaries/26777_01_Allison_%26_Harbour_CH_01.pdf',
  inner: 'https://dev.theinnergame.com/the-power-of-your-imagination/',
  microsoft: 'https://coachingfederation.org/wp-content/uploads/2026/01/icf-awards-microsoft-case-study-1.pdf',
  intel: 'https://coachingfederation.org/wp-content/uploads/2025/02/icf-awards-intel-corporation-case-study.pdf',
  astrazeneca: 'https://coachingfederation.org/app/uploads/2023/10/ICFCoachingImpactAwards2023_AZ_CaseStudy-final.pdf',
  rct: 'https://research.vu.nl/en/publications/what-can-we-know-about-the-effectiveness-of-coaching-a-meta-analy/',
  review: 'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2023.1089797/full'
};
export const lessons = [
  {
    id:'c1', slug:'competenta-1-etica.html', title:p('Practică etică','Ethical practice'), group:p('Fundamente','Foundation'), video:'-WBkKvHP24M', page:3,
    intro:p('Un proces de coaching începe cu o relație în care oamenii știu la ce consimt. Etica se vede în alegerile mici: ce promiți, ce păstrezi, cui răspunzi și când recunoști că nu ești persoana potrivită.','A coaching process begins with a relationship in which people know what they are consenting to. Ethics shows up in small choices: what you promise, what you retain, whom you answer to and when you recognise that you are not the right professional.'),
    concepts:[
      p('Claritate de rol. Dacă un client cere un diagnostic, o recomandare tehnică sau o decizie în locul lui, clarifică solicitarea. Competența într-un alt domeniu nu schimbă automat acordul de coaching.','Role clarity. If a client asks for a diagnosis, technical recommendation or decision on their behalf, clarify the request. Expertise in another field does not automatically change the coaching agreement.'),
      p('Confidențialitate concretă. Discutați ce poate ajunge la sponsor, cum sunt păstrate notițele și ce limite are confidențialitatea. Plata de către companie nu oferă automat acces la conținutul sesiunilor.','Concrete confidentiality. Discuss what may reach the sponsor, how notes are kept and the limits of confidentiality. Company funding does not automatically grant access to session content.'),
      p('Onestitate profesională. Prezintă exact pregătirea și experiența pe care le ai. Când observi că nevoia depășește competența ta, explorează cu clientul o trimitere către un profesionist potrivit.','Professional honesty. Describe your actual training and experience accurately. When the need exceeds your competence, explore referral to an appropriate professional with the client.')
    ],
    do:p('Înaintea unui program plătit de angajator, conveniți explicit ce indicatori de progres pot fi comunicați și cum participă clientul la raportare. Verifică acordul înainte să răspunzi unei solicitări noi.','Before an employer-funded engagement, explicitly agree what progress information may be shared and how the client participates in reporting. Revisit the agreement before answering a new request.'),
    avoid:p('Nu trimite notițele private pentru că „HR-ul a plătit”. Nu promite transformări garantate și nu prezenta un curs scurt ca echivalent cu o credențială profesională.','Do not share private notes because “HR paid for it”. Avoid guaranteed transformation claims or presenting a short course as equivalent to a professional credential.'),
    client:p('Managerul meu vrea să știe dacă am discutat despre plecarea din companie.','My manager wants to know whether we discussed leaving the company.'),
    coach:p('Să revenim la ce am stabilit despre raportare. Ce ai vrea să comunici tu și ce e important să rămână în această conversație?','Let’s return to our reporting agreement. What would you like to communicate yourself, and what matters to keep within this conversation?'),
    why:p('Coachul face vizibil acordul și autonomia clientului. Nu negociază în secret cu sponsorul și nu promite o excepție pe care nu o poate susține.','The coach makes the agreement and client autonomy visible. They do not negotiate secretly with the sponsor or promise an exception they cannot honour.'),
    questions:[p('Cine primește informații despre acest proces și ce am convenit concret?','Who receives information about this process, and what exactly have we agreed?'),p('Ce așteptare trebuie clarificată înainte să continuăm?','Which expectation needs clarification before we continue?'),p('Ce sprijin ar răspunde cel mai bine nevoii tale acum?','What support would best meet your need now?')],
    watch:p('Observă cum sunt legate deciziile etice de relația cu clientul, sponsorul și standardele profesiei.','Notice how ethical decisions connect the client, the sponsor and professional standards.')
  },
  {
    id:'c2',slug:'competenta-2-mentalitate.html',title:p('Mentalitatea coachului','The coaching mindset'),group:p('Fundamente','Foundation'),video:'1hwdbVA0Lns',page:4,
    intro:p('Clientul nu trebuie să trăiască viața pe care coachul o consideră corectă. Mentalitatea de coaching presupune să observi ce aduci tu în conversație: preferințe, graba de a ajuta, nevoia de a avea dreptate sau disconfortul de a nu ști.','The client does not have to live the life the coach considers right. A coaching mindset means noticing what you bring into the conversation: preferences, urgency to help, the need to be right or discomfort with not knowing.'),
    concepts:[
      p('Curiozitate verificabilă. Când simți că „știi deja” problema, transformă concluzia într-o ipoteză. Clientul trebuie să poată corecta interpretarea ta fără să apere o alegere în fața ta.','Testable curiosity. When you feel you “already know” the problem, turn your conclusion into a hypothesis. The client should be able to correct your interpretation without defending their choice to you.'),
      p('Practică reflexivă. După o sesiune, separă observațiile de presupuneri: ce a spus clientul, ce ai simțit și ce ai făcut cu acea reacție. Mentor coachingul și supervizarea pot susține perspective pe care singur le ratezi.','Reflective practice. After a session, separate observations from assumptions: what the client said, what you felt and what you did with that reaction. Mentor coaching and supervision can reveal perspectives you miss alone.'),
      p('Dezvoltare continuă. Actualizarea din 2025 face mai explicită învățarea continuă, atenția la tehnologie și grija pentru propria capacitate de lucru. A fi curios nu înseamnă a lucra fără pregătire sau fără limite.','Continuing development. The 2025 update makes ongoing learning, awareness of technology and attention to your capacity to work more explicit. Curiosity does not mean working without preparation or boundaries.')
    ],
    do:p('Observi că favorizezi stabilitatea financiară. Îți recunoști această preferință și întrebi ce criterii contează pentru client, fără să alegi în locul lui. După sesiune explorezi reacția în reflecție sau supervizare.','You notice that you favour financial stability. Acknowledge that preference and ask what criteria matter to the client, without choosing for them. Explore your reaction through reflection or supervision afterwards.'),
    avoid:p('Nu numi alegerea clientului „autosabotaj” doar fiindcă tu nu ai face-o. Nu transforma experiența ta de viață într-o explicație universală.','Do not label the client’s choice “self-sabotage” simply because you would not make it. Avoid treating your life experience as a universal explanation.'),
    client:p('Vreau să trec de la management la un rol de specialist. Toți spun că e un pas înapoi.','I want to move from management to an individual contributor role. Everyone says it is a step backwards.'),
    coach:p('Ce înseamnă pentru tine un pas înainte, în etapa aceasta a vieții?','What does moving forward mean to you at this stage of your life?'),
    why:p('Întrebarea explorează definiția clientului despre progres. Nu îi confirmă automat decizia și nici nu o măsoară cu valorile coachului.','The question explores the client’s definition of progress. It neither automatically endorses the decision nor measures it against the coach’s values.'),
    questions:[p('Ce presupun acum despre acest om?','What am I assuming about this person?'),p('Ce criterii sunt ale tale și ce criterii vin din așteptările altora?','Which criteria are yours, and which come from others’ expectations?'),p('Ce informație mi-ar putea schimba interpretarea?','What information might change my interpretation?')],
    watch:p('Urmărește distincția dintre o tehnică folosită în sesiune și felul în care coachul își dezvoltă practica în timp.','Notice the distinction between a technique used in a session and the way the coach develops their practice over time.')
  },
  {
    id:'c3',slug:'competenta-3-acorduri.html',title:p('Acordul de coaching','The coaching agreement'),group:p('Relația de coaching','The coaching relationship'),video:'5HFpPR5gXo0',page:5,
    intro:p('Un subiect nu este încă un acord. „Vreau să vorbesc despre job” spune unde începe discuția, dar nu ce ar face-o utilă. Acordul ajută clientul și coachul să aleagă împreună direcția și să recunoască progresul.','A topic is not yet an agreement. “I want to talk about work” tells you where the conversation begins, but not what would make it useful. An agreement helps client and coach choose a direction together and recognise progress.'),
    concepts:[
      p('Două niveluri. Colaborarea are un cadru general: roluri, obiective, durată, condiții și raportare. Fiecare sesiune are un acord local: cu ce vrea persoana să plece astăzi și de ce contează.','Two levels. The engagement has an overall framework: roles, goals, duration, terms and reporting. Each session has a local agreement: what the person wants to leave with today and why it matters.'),
      p('Un reper observabil. „Mai multă claritate” poate însemna trei criterii pentru o alegere, identificarea unei conversații de purtat sau înțelegerea unei ezitări. Întreabă ce înseamnă pentru client, fără să impui un indicator numeric.','An observable reference point. “More clarity” might mean three decision criteria, identifying a conversation to have or understanding a hesitation. Ask what it means to the client without imposing a numeric measure.'),
      p('Acord viu. Dacă apare un subiect mai important, opriți-vă și decideți dacă schimbați direcția. În versiunea 2025, revizuirea acordului apare explicit; întoarcerea la scop nu trebuie să devină rigiditate.','A living agreement. If something more important emerges, pause and decide whether to change direction. Revisiting the agreement is explicit in the 2025 version; returning to the purpose should not become rigidity.')
    ],
    do:p('Clarifică rezultatul dorit, sensul lui și semnul de utilitate. Dacă discuția se mută, întreabă clientul ce preferă să exploreze în timpul rămas.','Clarify the desired outcome, its meaning and the sign of usefulness. If the conversation shifts, ask what the client prefers to explore in the time remaining.'),
    avoid:p('Nu decide că obiectivul este „să delegi mai mult” doar fiindcă ai identificat o problemă de delegare. Nu continua mecanic cu obiectivul inițial după ce clientul spune că altceva contează mai mult.','Do not decide the goal is “delegate more” just because you identified a delegation problem. Do not mechanically pursue the initial goal after the client says something else matters more.'),
    client:p('Am cinci probleme cu echipa și nu știu de unde să încep.','I have five problems with my team and do not know where to start.'),
    coach:p('Dacă în cele 40 de minute am clarifica un singur lucru, care ar face cea mai mare diferență pentru tine? Cum ai recunoaște că l-am clarificat?','If we clarified one thing in these 40 minutes, which would make the biggest difference for you? How would you recognise that we had clarified it?'),
    why:p('Coachul invită prioritizarea și un criteriu al clientului. Întrebările se adresează pe rând, lăsând spațiu pentru răspuns.','The coach invites prioritisation and a client-defined criterion. Ask these questions one at a time, leaving space for an answer.'),
    questions:[p('Cu ce vrei să pleci din această conversație?','What do you want to leave this conversation with?'),p('De ce este important tocmai acum?','Why does this matter now?'),p('Continuăm aici sau vrei să schimbăm acordul de azi?','Do we continue here, or would you like to change today’s agreement?')],
    watch:p('Ascultă diferența dintre contractarea întregului proces și acordul pentru sesiunea de astăzi.','Listen for the difference between contracting the overall engagement and agreeing on today’s session.')
  },
  {
    id:'c4',slug:'competenta-4-incredere.html',title:p('Încredere și siguranță','Trust and safety'),group:p('Relația de coaching','The coaching relationship'),video:'kwb9PjIHYAA',page:6,
    intro:p('Siguranța se construiește prin felul în care răspunzi când clientul nu este de acord, nu știe sau nu vrea să continue un subiect. O atmosferă caldă ajută, dar nu înlocuiește respectul pentru limite și pentru diferențe.','Safety is built through how you respond when a client disagrees, does not know or does not want to continue a topic. Warmth helps, but it does not replace respect for boundaries and differences.'),
    concepts:[
      p('Persoana în context. Întreabă ce înseamnă situația în cultura, echipa sau familia clientului. Același comportament poate avea sensuri diferite; familiaritatea ta cu tema nu îți oferă acces direct la experiența lui.','The person in context. Ask what the situation means in the client’s culture, team or family. The same behaviour can have different meanings; familiarity with the topic does not give you direct access to their experience.'),
      p('Permisiunea de a refuza. O invitație reală poate primi „nu”. Clientul poate să corecteze o observație, să încetinească sau să oprească explorarea fără să fie etichetat drept rezistent.','Permission to decline. A real invitation can receive a “no”. The client can correct an observation, slow down or stop exploring without being labelled resistant.'),
      p('Sprijin și provocare. Poți recunoaște dificultatea fără să confirmi toate interpretările clientului. O provocare utilă este oferită cu grijă și libertate de răspuns, nu ca verdict despre caracter.','Support and challenge. You can acknowledge difficulty without endorsing every interpretation. A helpful challenge is offered with care and freedom to respond, not as a verdict about character.')
    ],
    do:p('Cere permisiunea înaintea unei observații sensibile. Dacă ai înțeles greșit, recunoaște simplu și lasă clientul să reformuleze. Ajustează ritmul la ceea ce spune că îi este util.','Ask permission before a sensitive observation. If you misunderstood, acknowledge it simply and let the client restate it. Adjust the pace to what they say is useful.'),
    avoid:p('Nu forța vulnerabilitatea: „Dacă nu-mi spui tot, nu putem lucra”. Nu confunda susținerea cu aprobarea automată sau cu promisiunea că persoana se va simți mereu confortabil.','Do not force vulnerability: “If you do not tell me everything, we cannot work.” Do not confuse support with automatic approval or a promise of constant comfort.'),
    client:p('Nu vreau să intru în detalii despre familia mea.','I do not want to go into details about my family.'),
    coach:p('În regulă. Ce parte a situației de la muncă ai vrea să explorăm în limitele care îți sunt potrivite?','All right. What part of the work situation would you like to explore within boundaries that fit you?'),
    why:p('Limita este acceptată, iar conversația rămâne în parteneriat. Coachul nu interpretează refuzul ca simptom sau ca lipsă de angajament.','The boundary is accepted and the conversation remains a partnership. The coach does not interpret refusal as a symptom or lack of commitment.'),
    questions:[p('Ce ai nevoie de la mine ca discuția să îți fie utilă?','What do you need from me for this conversation to be useful?'),p('Pot să îți ofer o observație pe care o poți corecta?','May I offer an observation that you are free to correct?'),p('Ce nu am înțeles bine din perspectiva ta?','What have I misunderstood from your perspective?')],
    watch:p('Observă cum încrederea presupune respect pentru identitate și context, nu doar amabilitate.','Notice how trust involves respect for identity and context, as well as kindness.')
  },
  {
    id:'c5',slug:'competenta-5-prezenta.html',title:p('Prezență în conversație','Presence in the conversation'),group:p('Relația de coaching','The coaching relationship'),video:'09xBvXkbfRE',page:7,
    intro:p('Prezența înseamnă să rămâi disponibil pentru ceea ce se întâmplă acum, chiar dacă nu se potrivește planului tău. Uneori intervenția utilă este o întrebare; alteori este o pauză sau recunoașterea faptului că ai pierdut firul.','Presence means remaining available to what is happening now, even when it does not fit your plan. Sometimes the useful intervention is a question; sometimes it is a pause or acknowledging that you lost the thread.'),
    concepts:[
      p('Atenție dublă. Urmărește clientul și observă-ți propriile reacții. Dacă te grăbești, te simți evaluat sau vrei să salvezi situația, acea reacție poate influența următoarea intervenție.','Dual attention. Follow the client while noticing your own reactions. If you rush, feel evaluated or want to rescue the situation, that reaction can shape your next intervention.'),
      p('Flexibilitate cu direcție. Un model te poate orienta, dar nu trebuie să îți ocupe toată atenția. Poți schimba ritmul și poți renegocia direcția păstrând acordul cu clientul.','Flexibility with direction. A model can guide you without taking all your attention. You can change pace and renegotiate direction while maintaining agreement with the client.'),
      p('Tăcere cu sens. Nu există un număr magic de secunde. Observă dacă pauza ajută reflecția și verifică, atunci când este potrivit. Prezența nu înseamnă să privești în tăcere indiferent de nevoia persoanei.','Meaningful silence. There is no magic number of seconds. Notice whether a pause helps reflection and check when appropriate. Presence does not mean staring silently regardless of the person’s needs.')
    ],
    do:p('Când clientul se emoționează, redu ritmul, rămâi atent și întreabă ce i-ar fi util acum. Lasă loc răspunsului înainte să propui o direcție.','When the client becomes emotional, slow down, stay attentive and ask what would be useful now. Leave room for an answer before proposing a direction.'),
    avoid:p('Nu umple fiecare pauză cu o întrebare nouă. Nu oferi imediat reasigurări precum „sigur va fi bine” doar ca să îți reduci propriul disconfort.','Do not fill every pause with a new question. Avoid immediate reassurance such as “it will be fine” merely to reduce your own discomfort.'),
    client:p('Credeam că problema este timpul… acum îmi dau seama că mi-e teamă să spun nu.','I thought time was the problem… now I realise I am afraid to say no.'),
    coach:p('Putem să rămânem puțin cu ce ai observat. Ce devine important pentru tine acum?','We can stay with what you have noticed for a moment. What becomes important for you now?'),
    why:p('Coachul urmărește schimbarea de sens și oferă spațiu. Nu revine automat la lista de tehnici de management al timpului.','The coach follows the shift in meaning and offers space. They do not automatically return to a list of time-management techniques.'),
    questions:[p('Ce se întâmplă pentru tine în acest moment?','What is happening for you at this moment?'),p('Ar fi util să mai lăsăm puțin spațiu?','Would leaving a little more space be helpful?'),p('Ce ai vrea să urmărim din ce a apărut acum?','What would you like to follow from what has just emerged?')],
    watch:p('Urmărește cum este descrisă atenția la ceea ce apare în coach și în client în momentul prezent.','Notice how attention to what emerges in both coach and client in the present moment is described.')
  },
  {
    id:'c6',slug:'competenta-6-ascultare.html',title:p('Ascultare activă','Active listening'),group:p('Comunicare','Communication'),video:'EYoes3Nmbz8',page:8,
    intro:p('A asculta activ înseamnă să urmărești sensul pe care clientul îl dă experienței sale. Cuvintele, tonul și pauzele oferă indicii. Sensul lor se verifică împreună; nu se ghicește dintr-un gest.','Active listening means following the meaning the client gives their experience. Words, tone and pauses offer clues. Their meaning is checked together, not guessed from a gesture.'),
    concepts:[
      p('Cuvinte cu semnificație personală. „Succes”, „respect” sau „siguranță” pot însemna lucruri diferite pentru doi oameni. Păstrează termenul clientului și invită-l să îl definească.','Personally meaningful words. “Success”, “respect” or “security” can mean different things to different people. Retain the client’s term and invite them to define it.'),
      p('Reflecție scurtă, verificabilă. Un rezumat bun îi permite clientului să se audă și să adauge ce lipsește. Nu transformă intervenția coachului într-un discurs despre ce a înțeles el.','Brief, checkable reflection. A useful summary lets the client hear themselves and add what is missing. It does not turn the coach’s intervention into a speech about their own understanding.'),
      p('Tipare și context. Observă cuvinte care revin sau diferențe între două situații. Oferă observația ca invitație, păstrând posibilitatea că există o explicație pe care încă nu o cunoști.','Patterns and context. Notice recurring words or differences between situations. Offer the observation as an invitation, allowing for an explanation you do not yet know.')
    ],
    do:p('Spune ce ai observat concret, apoi verifică semnificația. De exemplu: „Ai spus de trei ori că trebuie. Ce înseamnă acest trebuie pentru tine?”','State what you specifically noticed, then check its meaning. For example: “You have said ‘must’ three times. What does that ‘must’ mean to you?”'),
    avoid:p('Nu transforma postura în diagnostic: „Ai brațele încrucișate, deci ești defensiv”. Nu completa povestea cu propriile amintiri și nu formula următoarea întrebare în timp ce persoana încă vorbește.','Do not turn posture into a diagnosis: “Your arms are crossed, so you are defensive.” Avoid filling the story with your memories or planning the next question while the person is still speaking.'),
    client:p('Promovarea e extraordinară. Doar că… nu știu.','The promotion is wonderful. It is just that… I do not know.'),
    coach:p('Aud și entuziasm, și un „nu știu”. Ce ai vrea să înțeleg din partea aceasta?','I hear enthusiasm and an “I do not know”. What would you like me to understand about that part?'),
    why:p('Coachul reflectă cele două elemente exprimate și invită clarificarea. Nu presupune că ezitarea înseamnă refuzul promovării.','The coach reflects both expressed elements and invites clarification. They do not assume hesitation means rejecting the promotion.'),
    questions:[p('Când spui „respect”, cum se vede el concret?','When you say “respect”, what does it look like in practice?'),p('Ce am omis din ceea ce ai vrut să spui?','What have I missed in what you meant?'),p('Ce legătură vezi tu între aceste două situații?','What connection do you see between these two situations?')],
    watch:p('Urmărește diferența dintre a colecta informații și a asculta persoana în contextul ei.','Notice the difference between collecting information and listening to the person in their context.')
  },
  {
    id:'c7',slug:'competenta-7-constientizare.html',title:p('Conștientizare și perspective','Awareness and perspectives'),group:p('Comunicare','Communication'),video:'aoy2wtPhKYM',page:9,
    intro:p('Conștientizarea apare când clientul vede ceva relevant pe care nu îl observa înainte: o presupunere, o nevoie, o resursă sau o posibilitate. Coachul poate contribui prin întrebări, observații și metafore, fără să stabilească dinainte ce trebuie descoperit.','Awareness emerges when the client notices something relevant they had not seen before: an assumption, need, resource or possibility. The coach can contribute questions, observations and metaphors without deciding in advance what must be discovered.'),
    concepts:[
      p('O întrebare deschide spațiu. „Cum ai putea să delegi?” conține deja o direcție. Dacă clientul încă explorează problema, „Ce opțiuni ai?” poate oferi mai multă libertate. Alegerea depinde de acord și de moment.','A question opens space. “How could you delegate?” already contains a direction. If the client is still exploring the problem, “What options do you have?” may offer more freedom. The choice depends on the agreement and the moment.'),
      p('Provocare fără verdict. Poți observa o tensiune între două afirmații și întreba cum o înțelege clientul. Nu trebuie să dovedești că ai descoperit adevărul ascuns despre el.','Challenge without a verdict. You can notice tension between two statements and ask how the client understands it. You do not need to prove that you discovered a hidden truth about them.'),
      p('Integrare, nu spectacol. Un insight mic poate schimba o decizie. După o observație importantă, lasă clientul să formuleze ce înseamnă și verifică relevanța pentru obiectiv. Nu vâna emoții intense ca dovadă de progres.','Integration, not spectacle. A small insight can change a decision. After an important observation, let the client articulate its meaning and check its relevance to the goal. Do not chase intense emotions as evidence of progress.')
    ],
    do:p('Oferă o observație cu permisiune și fără atașament: „Spui că vrei autonomie, dar verifici fiecare decizie. Ce vezi tu în această diferență?” Acceptă că observația poate să nu fie utilă.','Offer an observation with permission and without attachment: “You say you want autonomy, but check every decision. What do you see in that difference?” Accept that the observation may not be useful.'),
    avoid:p('Nu ascunde sfatul într-o întrebare: „Nu crezi că ar trebui să ai mai mult curaj?” Nu impune o explicație despre subconștientul clientului pe baza unei singure replici.','Do not hide advice in a question: “Don’t you think you should be braver?” Avoid imposing an explanation about the client’s unconscious based on a single remark.'),
    client:p('Dacă nu verific eu, lucrurile sigur ies prost.','If I do not check, things will definitely go wrong.'),
    coach:p('Când ai lăsat pe cineva să decidă și lucrurile au mers suficient de bine? Ce a fost diferit atunci?','When have you let someone decide and things went well enough? What was different then?'),
    why:p('Clientul este invitat să caute experiențe care pot nuanța o regulă absolută. Coachul nu afirmă că orice delegare este bună sau lipsită de risc.','The client is invited to find experiences that may qualify an absolute rule. The coach does not claim that every delegation is good or risk-free.'),
    questions:[p('Ce presupui că este obligatoriu aici?','What are you assuming is compulsory here?'),p('Ce altă explicație merită verificată?','What other explanation is worth checking?'),p('Ce observi acum despre felul în care alegi?','What do you notice now about how you choose?')],
    watch:p('Observă varietatea intervențiilor: întrebarea este un instrument, alături de tăcere, observație și analogie.','Notice the range of interventions: questioning is one tool alongside silence, observation and analogy.')
  },
  {
    id:'c8',slug:'competenta-8-crestere.html',title:p('Învățare transformată în progres','Turning learning into progress'),group:p('Învățare și dezvoltare','Learning and growth'),video:'_B7VQA8WJxI',page:10,
    intro:p('O conversație utilă continuă în felul în care clientul gândește, decide sau acționează după sesiune. Coachul sprijină această trecere fără să devină șeful unui plan de teme. Progresul poate însemna și un experiment sau o observație deliberată.','A useful conversation continues in how the client thinks, decides or acts after the session. The coach supports this transition without becoming the boss of a homework plan. Progress can also mean an experiment or deliberate observation.'),
    concepts:[
      p('Învățare formulată de client. Întreabă ce s-a schimbat în înțelegerea lui. Un rezumat perfect al coachului nu garantează că persoana și-a însușit ideea.','Learning articulated by the client. Ask what changed in their understanding. A perfect coach summary does not guarantee that the person has made the insight their own.'),
      p('Pas ales și realist. Explorați ce vrea să încerce, în ce context și cu ce sprijin. Includeți obstacolele reale: timp, competențe, putere de decizie sau resurse. Nu reduceți totul la voință.','A chosen, realistic step. Explore what they want to try, in what context and with what support. Include real obstacles: time, skills, decision-making power or resources. Do not reduce everything to willpower.'),
      p('Revizuire care produce învățare. La întâlnirea următoare, analizați ce s-a întâmplat și ce merită ajustat. Versiunea 2025 accentuează și susținerea progresului pe parcursul întregii colaborări.','Review that produces learning. At the next meeting, explore what happened and what needs adjustment. The 2025 version also emphasises supporting progress across the overall engagement.')
    ],
    do:p('Invită clientul să aleagă un experiment mic, un moment pentru el și un semn de învățare. Întreabă cum dorește să își urmărească angajamentul și ce sprijin i-ar fi util.','Invite the client to choose a small experiment, a time for it and a sign of learning. Ask how they want to track their commitment and what support would be useful.'),
    avoid:p('Nu prescrie o temă pentru a avea ceva de bifat. Dacă planul nu a fost încercat, evită rușinarea: „Nu te-ai implicat”. Explorează ce a împiedicat acțiunea și dacă planul încă are sens.','Do not prescribe homework just to have something to check off. If a plan was not tried, avoid shaming: “You were not committed.” Explore what prevented action and whether the plan still makes sense.'),
    client:p('Înțeleg că verific prea mult. Vreau să încerc altfel la următorul proiect.','I understand that I check too much. I want to try a different approach on the next project.'),
    coach:p('Ce experiment concret alegi pentru săptămâna aceasta? Ce ai vrea să observi ca să decizi ce păstrezi?','What specific experiment do you choose for this week? What would you like to observe to decide what to keep?'),
    why:p('Acțiunea aparține clientului și este legată de învățare. Rezultatul nu se măsoară doar prin executarea unei instrucțiuni.','The action belongs to the client and is connected to learning. The outcome is not measured solely by following an instruction.'),
    questions:[p('Ce iei cu tine din conversația de azi?','What are you taking from today’s conversation?'),p('Care este cel mai mic pas relevant pe care îl alegi?','What is the smallest relevant step you choose?'),p('Cum vei folosi ce observi, indiferent cum iese experimentul?','How will you use what you notice, whatever happens in the experiment?')],
    watch:p('Urmărește legătura dintre autonomie, învățare și felul în care se încheie sesiunea.','Notice the connection between autonomy, learning and how the session ends.')
  }
];

// The same fictional delegation situation continues through all four stages.
export const grow = [
 {letter:'G',word:'Goal',title:p('Alege direcția','Choose the direction'),prompt:p('Ce vrei să devină posibil?','What do you want to make possible?'),text:p('Clarifică rezultatul util al conversației și de ce contează acum. Un obiectiv poate fi și o decizie mai clară, nu doar un indicator de performanță.','Clarify a useful outcome for the conversation and why it matters now. A goal may be a clearer decision, as well as a performance measure.'),questions:[p('Cu ce claritate ai vrea să pleci astăzi?','What clarity would you like to leave with today?'),p('Ce ar face diferența pentru tine?','What would make a difference for you?'),p('Cum vei recunoaște că discuția ți-a fost utilă?','How will you recognise that the conversation was useful?')],example:p('Andrei: „Vreau să aleg ce pot delega săptămâna aceasta și ce acord să fac cu echipa.”','Andrei: “I want to choose what I can delegate this week and what agreement to make with the team.”'),avoid:p('Să impui propriul obiectiv: „Deci trebuie să delegi 50%.”','Imposing your own goal: “So you need to delegate 50%.”')},
 {letter:'R',word:'Reality',title:p('Privește ce este','See what is happening'),prompt:p('Ce se întâmplă concret?','What is actually happening?'),text:p('Separă faptele de interpretări. Explorează resursele, constrângerile și ceea ce a fost încercat. Rămâi curios și față de ceea ce funcționează.','Separate facts from interpretations. Explore resources, constraints and previous attempts. Stay curious about what already works.'),questions:[p('Cum a arătat ultima situație concretă?','What did the last specific situation look like?'),p('Ce știi sigur și ce presupui?','What do you know and what are you assuming?'),p('Când a mers mai bine și ce era diferit?','When did it go better and what was different?')],example:p('Andrei aprobă orice livrabil, dar două sarcini au fost rezolvate bine fără el. Observă că standardul de calitate nu a fost discutat explicit.','Andrei approves every deliverable, yet two tasks went well without him. He notices that the quality standard was never explicitly discussed.'),avoid:p('Să transformi explorarea într-un interogatoriu sau să etichetezi: „Ești un micromanager.”','Turning exploration into an interrogation or labelling: “You are a micromanager.”')},
 {letter:'O',word:'Options',title:p('Deschide posibilități','Open possibilities'),prompt:p('Ce ai putea încerca?','What could you try?'),text:p('Lasă loc mai multor variante înainte de selecție. Clientul poate combina, testa sau respinge opțiunile. Dacă oferi o idee, cere permisiunea și nu te atașa de ea.','Allow several alternatives before selecting. The client may combine, test or reject options. If you offer an idea, ask permission and do not become attached to it.'),questions:[p('Ce variante merită puse pe masă?','What possibilities are worth considering?'),p('Ce ai mai putea încerca, chiar la scară mică?','What else could you try, even on a small scale?'),p('Ce câștigi și la ce renunți cu fiecare variantă?','What do you gain and give up with each option?')],example:p('Andrei propune: un checklist comun, o verificare intermediară sau delegarea completă a unei sarcini cu risc mic. Compară variantele după criteriile lui.','Andrei proposes a shared checklist, an interim check-in or fully delegating a low-risk task. He compares them using his own criteria.'),avoid:p('Să accepți doar alternativa pe care o aveai tu în minte.','Only accepting the alternative you already had in mind.')},
 {letter:'W',word:'Will / Way forward',title:p('Alege un pas','Choose a step'),prompt:p('Ce alegi și cum vei învăța?','What do you choose and how will you learn?'),text:p('Leagă alegerea de un moment, de sprijin și de un mod de revizuire. Verifică disponibilitatea reală; un plan ambițios fără acord nu este un angajament.','Connect the choice to a time, support and a way to review. Check actual willingness; an ambitious plan without agreement is not a commitment.'),questions:[p('Ce alegi să testezi până la următoarea întâlnire?','What do you choose to test before the next meeting?'),p('Ce obstacol anticipezi și ce sprijin vrei?','What obstacle do you anticipate and what support do you want?'),p('Când vei verifica ce ai învățat?','When will you review what you learned?')],example:p('Marți, Andrei deleagă raportul săptămânal, agreează criteriile și o singură verificare. Vineri reflectează cu colegul: ce a mers și ce ajustăm?','On Tuesday, Andrei delegates the weekly report, agrees criteria and one check-in. On Friday he reflects with his colleague: what worked and what should we adjust?'),avoid:p('Să ceri promisiuni ca să închei frumos sesiunea, fără să verifici realismul planului.','Asking for promises to end the session neatly without checking whether the plan is realistic.')}
];
