import {p,sources} from './learning-content.mjs';

export const models = [
 {id:'clear',name:'CLEAR',author:'Peter Hawkins · Hawkins & Smith',
  subtitle:p('Acord, ascultare și revizuire','Agreement, listening and review'),
  purpose:p('Un cadru care pune în prim-plan relația de lucru și felul în care este revizuită conversația. Este folosit în coaching și supervizare; nu reprezintă un standard de certificare ICF.','A framework that foregrounds the working relationship and how the conversation is reviewed. Used in coaching and supervision, it is not an ICF credentialing standard.'),
  steps:[
   ['C','Contracting',p('Stabiliți ce lucru util aveți de făcut și cum veți colabora.','Agree what useful work needs doing and how you will work together.'),p('Ce vrei să obții și de ce ai nevoie de la mine?','What do you want to achieve and what do you need from me?')],
   ['L','Listening',p('Ascultă experiența și sensul pe care persoana îl dă situației.','Listen to the experience and the meaning the person gives it.'),p('Ce este cel mai important să înțeleg?','What is most important for me to understand?')],
   ['E','Exploring',p('Explorați presupunerile, efectele și variantele de răspuns.','Explore assumptions, effects and possible responses.'),p('Ce se repetă și ce ai putea încerca diferit?','What repeats and what could you try differently?')],
   ['A','Action',p('Clientul decide ce vrea să testeze sau să schimbe.','The client decides what to test or change.'),p('Ce alegi să pui în practică?','What do you choose to put into practice?')],
   ['R','Review',p('Revizuiți învățarea și utilitatea felului în care ați lucrat.','Review the learning and the usefulness of how you worked.'),p('Ce a fost util și ce ajustăm în conversația următoare?','What was useful and what should we adjust next time?')]
  ],
  example:p('Exemplu fictiv: Irina evită o discuție cu un coleg. Agreați să clarifice cum vrea să intre în conversație. Ascultând situația, observă că pregătește contraargumente înainte să audă ce spune celălalt. Explorează alternativa de a verifica întâi ce a înțeles. Alege să testeze o recapitulare scurtă la următoarea întâlnire. La final numește ce a învățat și cere mai puține întrebări consecutive din partea coachului.','Fictional example: Irina avoids a conversation with a colleague. You agree to clarify how she wants to enter it. While discussing the situation, she notices that she prepares counterarguments before hearing the other person. She explores checking her understanding first, then chooses to test a brief recap at the next meeting. At the end, she names her learning and asks the coach to use fewer consecutive questions.'),
  use:p('Reper editorial: când merită să acorzi atenție felului în care colaborați, inclusiv feedbackului despre sesiune.','Editorial suggestion: when the way you work together deserves attention, including feedback about the session.'),
  pitfall:p('Nu sări peste Review și nu transforma Listening într-o simplă colectare de date pentru soluția ta. Contracting se poate relua când nevoia se schimbă.','Do not skip Review or turn Listening into collecting data for your solution. Contracting can be revisited when the need changes.'),
  source:sources.clear,sourceName:p('Henley Business School · CLEAR în supervizare, 2019','Henley Business School · CLEAR in supervision, 2019')
 },
 {id:'oskar',name:'OSKAR',author:'Paul Z Jackson & Mark McKergow · The Solutions Focus',
  subtitle:p('Pornește de la ce funcționează','Start with what works'),
  purpose:p('Un model orientat spre soluții: descrii viitorul dorit, identifici ce există deja și alegi un pas mic. Scala este o estimare personală ancorată în exemple, nu un test psihologic sau o măsură obiectivă de performanță.','A solution-focused model: describe the desired future, identify what is already there and choose a small step. The scale is a personal estimate grounded in examples, not a psychological test or objective performance measure.'),
  steps:[
   ['O','Outcome',p('Descrie rezultatul în termeni concreți pentru client.','Describe the outcome in terms meaningful to the client.'),p('Ce ai observa diferit dacă lucrurile ar merge suficient de bine?','What would you notice if things were going well enough?')],
   ['S','Scaling',p('Alegeți repere pentru o scală și explorați poziția actuală.','Choose anchors for a scale and explore the current position.'),p('Dacă 10 descrie rezultatul dorit, unde ești acum și ce susține acest număr?','If 10 describes your desired outcome, where are you now and what supports that number?')],
   ['K','Know-how',p('Căutați resurse și excepții: momente când a fost mai bine.','Look for resources and exceptions: times when it was better.'),p('Ce faci deja care te ține la acest nivel?','What do you already do that keeps you at this level?')],
   ['A','Affirm & Action',p('Recunoașteți ce ajută și alegeți un pas bazat pe asta.','Acknowledge what helps and choose a step based on it.'),p('Ce ai putea repeta sau extinde puțin?','What could you repeat or extend a little?')],
   ['R','Review',p('Observați progresul și cum a fost posibil.','Notice progress and how it became possible.'),p('Ce este mai bine și cum ai contribuit la asta?','What is better and how did you contribute to it?')]
  ],
  example:p('Exemplu fictiv: Radu își evaluează participarea în ședințe la 4 din 10. În loc să trateze scorul ca pe un eșec, explorează de ce nu este 2. Descoperă că vorbește mai ușor când pregătește o întrebare și primește agenda înainte. Alege să ceară agenda și să pregătească o intervenție. La următoarea sesiune discută ce a observat, inclusiv dacă scala nu s-a schimbat.','Fictional example: Radu rates his participation in meetings at 4 out of 10. Instead of treating the score as failure, he explores why it is not 2. He finds that he speaks more easily when he prepares a question and receives the agenda beforehand. He chooses to request the agenda and prepare one contribution. At the next session, he discusses what he noticed, including if the scale has not changed.'),
  use:p('Reper editorial: când persoana poate descrie un rezultat și are experiențe sau resurse pe care le poate extinde.','Editorial suggestion: when the person can describe an outcome and has experiences or resources they can build on.'),
  pitfall:p('Orientarea spre soluții nu justifică ignorarea suferinței sau a constrângerilor. Nu forța un scor mai mare și nu transforma recunoașterea resurselor în pozitivitate obligatorie.','A solution focus does not justify ignoring distress or constraints. Do not force a higher score or turn recognition of resources into compulsory positivity.'),
  source:sources.oskar,sourceName:p('The Solutions Focus · prezentarea modelului de către autori','The Solutions Focus · the authors’ presentation of the model')
 },
 {id:'inner-game',name:'Inner Game',author:'W. Timothy Gallwey · The Inner Game of Tennis',
  subtitle:p('Atenție, interferență și învățare','Attention, interference and learning'),
  purpose:p('O abordare a învățării și performanței, nu o succesiune obligatorie de întrebări. Gallwey descrie diferența dintre comentariul interior și capacitatea de a executa și a învăța. „Self 1” și „Self 2” sunt o metaforă de lucru; nu două entități demonstrate în creier.','An approach to learning and performance, not a mandatory sequence of questions. Gallwey describes a distinction between inner commentary and the capacity to perform and learn. “Self 1” and “Self 2” are a working metaphor, not two demonstrated entities in the brain.'),
  steps:[
   ['1',p('Observă','Notice'),p('Identifică o observație concretă, fără verdict global.','Identify a concrete observation without a global judgment.'),p('Ce ai observat efectiv, înainte să te evaluezi?','What did you actually notice before evaluating yourself?')],
   ['2',p('Alege atenția','Choose your focus'),p('Alege un indiciu relevant pentru activitatea reală.','Choose a cue relevant to the actual task.'),p('La ce ai putea fi atent în următoarea încercare?','What could you pay attention to on the next attempt?')],
   ['3',p('Experimentează','Experiment'),p('Testează și observă rezultatul; ajustează apoi.','Test and observe the result, then adjust.'),p('Ce s-a schimbat și ce vrei să păstrezi?','What changed and what would you like to keep?')]
  ],
  example:p('Exemplu public din tradiția cărții: exercițiul „bounce–hit” mută atenția jucătorului spre momentul în care mingea atinge terenul și racheta. Adaptare fictivă: înaintea unei prezentări, Mara înlocuiește eticheta „sunt slabă la vorbit” cu observația „accelerez în primul minut”. La următoarea repetiție urmărește pauza dintre două idei și compară experiența. Acesta este un experiment, nu o promisiune că emoțiile dispar.','Public example from the book’s tradition: the “bounce–hit” exercise directs a player’s attention to when the ball touches the court and racket. Fictional adaptation: before a presentation, Mara replaces “I am bad at speaking” with “I speed up in the first minute”. In the next rehearsal, she attends to the pause between two ideas and compares the experience. This is an experiment, not a promise that emotions disappear.'),
  use:p('Reper editorial: când autoevaluarea repetitivă ocupă atenția necesară unei sarcini pe care persoana o poate practica. Pașii de mai sus sunt o adaptare didactică CoachingHub.','Editorial suggestion: when repetitive self-evaluation consumes attention needed for a task the person can practise. The steps above are a CoachingHub teaching adaptation.'),
  pitfall:p('Nu afirma că orice limită este „doar în minte”. Competențele, pregătirea, sănătatea și condițiile de lucru rămân relevante. Exemplul din sport nu demonstrează automat eficiența unei intervenții organizaționale.','Do not claim that every limit is “only in the mind”. Skills, preparation, health and working conditions still matter. A sporting example does not automatically establish the effectiveness of an organisational intervention.'),
  source:sources.inner,sourceName:p('The Inner Game · exemplul public „bounce–hit”','The Inner Game · public “bounce–hit” example')
 }
];

// Under 200 words per case/source. All percentages retain their reported scope.
export const cases = [
 {id:'microsoft',name:'Microsoft · MCAPS',year:'2025',metric:'+34%',metricLabel:p('îmbunătățire medie raportată a comportamentelor de carieră','reported average improvement in career behaviours'),
  context:p('Accesul inițial era concentrat pe lideri și un grup restrâns de angajați cu potențial ridicat. Analiza experienței angajaților a indicat nevoia unui acces mai larg.','Initial access focused on leaders and a narrow group of high-potential employees. Analysis of employee experience indicated a need for broader access.'),
  action:p('Divizia Customer and Partner Solutions a extins coachingul individual, de grup și formarea managerilor. A susținut coachi interni și a integrat conversațiile în procesele de dezvoltare a carierei.','The Customer and Partner Solutions division expanded individual and group coaching and manager training. It supported internal coaches and integrated conversations into career development processes.'),
  result:p('Cazul ICF raportează o îmbunătățire medie de 34% a comportamentelor de carieră urmărite, inclusiv +51% în definirea pașilor de carieră. Evaluarea medie a coachilor a fost 4,9/5.','The ICF case reports an average 34% improvement in the career behaviours tracked, including +51% in defining career steps. The average coach rating was 4.9/5.'),
  limit:p('Date ale programului, prezentate într-un caz de premiu ICF. Nu sunt un experiment randomizat și nu înseamnă creștere de 34% a productivității sau a veniturilor Microsoft.','Programme data presented in an ICF award case. They are not a randomised experiment and do not mean a 34% increase in Microsoft productivity or revenue.'),
  lesson:p('Lecție editorială: accesul și integrarea în munca de zi cu zi merită proiectate la fel de atent ca sesiunile.','Editorial lesson: access and integration into everyday work deserve as much design attention as the sessions.'),source:sources.microsoft
 },
 {id:'intel',name:'Intel',year:'2022',metric:'91%',metricLabel:p('scor raportat pentru atingerea obiectivelor de business','reported score for achievement of business goals'),
  context:p('Intel a dezvoltat treptat un program intern pornit de la inițiativa unor angajați, cu accent pe manageri și lideri cu potențial ridicat.','Intel gradually developed an internal programme originating with employee initiative, focusing on managers and high-potential leaders.'),
  action:p('A combinat accesul la coachi, formarea abilităților de coaching și infrastructura de administrare. Evaluarea a folosit sondaje ale participanților și date despre retenție și dezvoltarea managerilor.','It combined access to coaches, coaching skills development and programme infrastructure. Evaluation used participant surveys and data on retention and manager development.'),
  result:p('Raportul menționează 1.100 de beneficiari direcți în 2021, un scor de 91% privind atingerea obiectivelor de business și o rată de promovare de 2,7 ori mai mare în rândul liderilor din program.','The report mentions 1,100 direct beneficiaries in 2021, a 91% score for achievement of business goals and a 2.7-times-higher promotion rate among programme leaders.'),
  limit:p('Indicatori interni raportați, fără randomizare descrisă. Selecția liderilor cu potențial și alți factori pot influența rezultatele; rata promovării nu dovedește singură efectul coachingului.','Reported internal measures without described randomisation. Selection of high-potential leaders and other factors can influence results; promotion rates alone do not establish the effect of coaching.'),
  lesson:p('Lecție editorială: definește de la început populația, nevoia și indicatorii; nu te opri la satisfacția față de sesiuni.','Editorial lesson: define the population, need and measures from the start; look beyond satisfaction with sessions.'),source:sources.intel
 },
 {id:'astrazeneca',name:'AstraZeneca',year:'2023',metric:'89%',metricLabel:p('dintre respondenți au simțit că și-au dezvoltat abilitățile','of respondents felt they developed their skills'),
  context:p('Un sondaj intern din 2020 a indicat că discuțiile de performanță erau percepute ca prea orientate spre trecut. Compania a urmărit un dialog mai util dezvoltării viitoare.','A 2020 internal survey indicated that performance conversations felt too focused on the past. The company sought dialogue more useful for future development.'),
  action:p('Strategia globală a inclus ateliere, învățare experiențială, resurse digitale și programele Manager as Coach și Leader as Coach, alături de coaching individual.','The global strategy included workshops, experiential learning, digital resources and Manager as Coach and Leader as Coach programmes alongside individual coaching.'),
  result:p('Cazul ICF menționează că 89% dintre respondenți au simțit că și-au dezvoltat abilitățile, iar 83% au perceput oportunități de dezvoltare personală.','The ICF case states that 89% of respondents felt they developed their skills and 83% perceived opportunities for personal development.'),
  limit:p('Sunt percepții ale participanților, nu măsurători independente ale performanței. Programul combină mai multe intervenții; nu putem atribui întregul rezultat coachingului individual.','These are participant perceptions, not independent performance measurements. The programme combines several interventions; the full result cannot be attributed to individual coaching.'),
  lesson:p('Lecție editorială: coachingul poate fi conectat la conversații recurente despre dezvoltare, cu verificarea experienței angajaților.','Editorial lesson: coaching can connect to recurring development conversations, with checks on employee experience.'),source:sources.astrazeneca
 }
];
